workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Lead Scraping Service API:
        inputs:
            - location: https://gateway.yoanyombapro.workers.dev/openapi
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/oppulence-backend/oppulence/lead-scraping-service-api
targets:
    oppulence-backend-sdk:
        target: typescript
        source: Lead Scraping Service API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/oppulence-backend/oppulence/lead-scraping-service-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
